import os

FAILURE_THRESHOLD = int(os.getenv("FAILURE_THRESHOLD", 3))
RECOVERY_TIMEOUT = int(os.getenv("RECOVERY_TIMEOUT_SECONDS", 10))
TEST_REQUESTS_ALLOWED = int(os.getenv("TEST_REQUESTS_ALLOWED_HALF_OPEN", 1))

MAX_RETRIES = int(os.getenv("MAX_RETRIES", 3))
INITIAL_BACKOFF = float(os.getenv("INITIAL_BACKOFF_SECONDS", 0.5))
BACKOFF_MULTIPLIER = float(os.getenv("BACKOFF_MULTIPLIER", 2))

RATE_LIMIT = int(os.getenv("RATE_LIMIT_REQUESTS_PER_WINDOW", 5))
RATE_WINDOW = int(os.getenv("RATE_LIMIT_WINDOW_SECONDS", 60))

FLAKY_URL = os.getenv("FLAKY_SERVICE_URL")
